module.exports=[81718,a=>{"use strict";var b=a.i(78347),c=a.i(64742);let d="https://best-upscaler-ia.vercel.app",e=["en","it","es","fr","de","pt","ru","ja","zh","ar","hi","ko"],f=new Date().toISOString().split("T")[0],g=[{path:"",priority:"1.0",changefreq:"daily"},{path:"/home",priority:"0.95",changefreq:"daily"},{path:"/tools",priority:"0.95",changefreq:"daily"},{path:"/upscaler",priority:"0.9",changefreq:"daily"},{path:"/pdf",priority:"0.9",changefreq:"daily"},{path:"/chat",priority:"0.85",changefreq:"daily"},{path:"/pricing",priority:"0.85",changefreq:"weekly"},{path:"/about",priority:"0.8",changefreq:"monthly"},{path:"/contact",priority:"0.75",changefreq:"monthly"},{path:"/faq",priority:"0.75",changefreq:"weekly"},{path:"/dashboard",priority:"0.7",changefreq:"weekly"},{path:"/login",priority:"0.6",changefreq:"monthly"},{path:"/signup",priority:"0.6",changefreq:"monthly"},{path:"/privacy",priority:"0.5",changefreq:"yearly"},{path:"/terms",priority:"0.5",changefreq:"yearly"}],h=[{path:"/pdf/jpg2pdf",priority:"0.85",changefreq:"daily"},{path:"/pdf/pdf2jpg",priority:"0.85",changefreq:"daily"},{path:"/pdf/docx2pdf",priority:"0.85",changefreq:"daily"},{path:"/pdf/pdf2docx",priority:"0.85",changefreq:"daily"},{path:"/pdf/ppt2pdf",priority:"0.8",changefreq:"weekly"},{path:"/pdf/pdf2pptx",priority:"0.8",changefreq:"weekly"},{path:"/pdf/xls2pdf",priority:"0.8",changefreq:"weekly"},{path:"/pdf/pdf2xlsx",priority:"0.8",changefreq:"weekly"},{path:"/pdf/html2pdf",priority:"0.75",changefreq:"weekly"},{path:"/pdf/pdf2pdfa",priority:"0.75",changefreq:"weekly"},{path:"/pdf/pdf2html",priority:"0.75",changefreq:"weekly"},{path:"/pdf/pdf2txt",priority:"0.75",changefreq:"weekly"}];function i(a,b="0.8",c="weekly",e=f){return`
    <url>
      <loc>${d}${a}</loc>
      <lastmod>${e}</lastmod>
      <changefreq>${c}</changefreq>
      <priority>${b}</priority>
    </url>`}async function j({res:a}){try{var j;let k,l=[];try{"function"==typeof c.getAllConversionTools&&(l=(0,c.getAllConversionTools)())}catch(a){console.warn("Error getting conversion tools:",a),l=[]}let m=(j=[...b.tools||[],...l],k=`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
  <!-- Static Pages -->`,g.forEach(a=>{k+=i(a.path,a.priority,a.changefreq),e.forEach(b=>{if("en"!==b){let c=`${a.path}`;k+=`
    <url>
      <loc>${d}${c}</loc>
      <xhtml:link rel="alternate" hreflang="${b}" href="${d}${c}" />
      <xhtml:link rel="alternate" hreflang="x-default" href="${d}${a.path}" />
      <lastmod>${f}</lastmod>
      <changefreq>${a.changefreq}</changefreq>
      <priority>${a.priority}</priority>
    </url>`}})}),k+=`
  <!-- PDF Conversion Pages -->`,h.forEach(a=>{k+=i(a.path,a.priority,a.changefreq)}),k+=`
  <!-- AI Tools Pages -->`,j.forEach(a=>{if(a.href){let b=a.pro?"0.9":"0.85",c="daily";["rimozione-sfondo-ai","generazione-immagini-ai","upscaler"].some(b=>a.href.includes(b))&&(b="0.95",c="daily"),k+=i(a.href,b,c)}}),k+=`
</urlset>`);a.setHeader("Content-Type","text/xml"),a.setHeader("Cache-Control","public, s-maxage=3600, stale-while-revalidate=86400"),a.write(m),a.end()}catch(b){console.error("Error generating sitemap:",b),a.statusCode=500,a.setHeader("Content-Type","text/xml"),a.write('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>'),a.end()}return{props:{}}}a.s(["default",0,function(){},"getServerSideProps",()=>j])},79603,a=>a.a(async(b,c)=>{try{var d=a.i(79168),e=a.i(27068),f=a.i(32759),g=a.i(31224),h=a.i(27342),i=a.i(81718),j=a.i(9193),k=b([h]);[h]=k.then?(await k)():k;let l=(0,f.hoist)(i,"default"),m=(0,f.hoist)(i,"getStaticProps"),n=(0,f.hoist)(i,"getStaticPaths"),o=(0,f.hoist)(i,"getServerSideProps"),p=(0,f.hoist)(i,"config"),q=(0,f.hoist)(i,"reportWebVitals"),r=(0,f.hoist)(i,"unstable_getStaticProps"),s=(0,f.hoist)(i,"unstable_getStaticPaths"),t=(0,f.hoist)(i,"unstable_getStaticParams"),u=(0,f.hoist)(i,"unstable_getServerProps"),v=(0,f.hoist)(i,"unstable_getServerSideProps"),w=new d.PagesRouteModule({definition:{kind:e.RouteKind.PAGES,page:"/sitemap.xml",pathname:"/sitemap.xml",bundlePath:"",filename:""},distDir:".next-build",relativeProjectDir:"",components:{App:h.default,Document:g.default},userland:i}),x=(0,j.getHandler)({srcPage:"/sitemap.xml",config:p,userland:i,routeModule:w,getStaticPaths:n,getStaticProps:m,getServerSideProps:o});a.s(["config",0,p,"default",0,l,"getServerSideProps",0,o,"getStaticPaths",0,n,"getStaticProps",0,m,"handler",0,x,"reportWebVitals",0,q,"routeModule",0,w,"unstable_getServerProps",0,u,"unstable_getServerSideProps",0,v,"unstable_getStaticParams",0,t,"unstable_getStaticPaths",0,s,"unstable_getStaticProps",0,r]),c()}catch(a){c(a)}},!1)];

//# sourceMappingURL=_9f12cf3d._.js.map