import {
    BsImage, BsArrowsAngleContract, BsFileEarmarkPdf, BsTextParagraph,
    BsType, BsFileText, BsSpellcheck, BsTextareaT, BsFileZip,
    BsCardImage, BsCameraVideo, BsSoundwave, BsStars, BsJournalCode, BsTranslate
} from 'react-icons/bs';

export const tools = [
    {
        title: 'Rimozione Sfondo AI',
        description: 'Rimuovi lo sfondo da qualsiasi immagine con un click.',
        icon: BsImage,
        href: '/tools/rimozione-sfondo-ai',
        category: 'Immagini',
        pro: true,
    },
    {
        title: 'Clean Noise AI',
        description: 'Rimuovi rumore di fondo e migliora la qualità dei tuoi audio.',
        icon: BsSoundwave,
        href: '/tools/clean-noise-ai',
        category: 'Audio',
        pro: true,
    },
    {
        title: 'Generazione Immagini AI',
        description: 'Crea immagini uniche da una descrizione testuale.',
        icon: BsStars,
        href: '/tools/generazione-immagini-ai',
        category: 'Immagini',
        pro: true,
    },
    {
        title: 'Trascrizione Audio',
        description: 'Converti file audio e vocali in testo modificabile.',
        icon: BsSoundwave,
        href: '/tools/trascrizione-audio',
        category: 'Audio',
    },
    {
        title: 'OCR Avanzato AI',
        description: 'Estrai testo da immagini, PDF e documenti scansionati.',
        icon: BsJournalCode,
        href: '/tools/ocr-avanzato-ai',
        category: 'Testo',
        pro: true,
    },
    {
        title: 'Traduzione Documenti AI',
        description: 'Traduci interi documenti mantenendo la formattazione.',
        icon: BsTranslate,
        href: '/tools/traduzione-documenti-ai',
        category: 'Testo',
        pro: true,
    },
    {
        title: 'Riassunto Testo',
        description: 'Sintetizza testi lunghi in riassunti chiari e concisi.',
        icon: BsTextParagraph,
        href: '/tools/riassunto-testo',
        category: 'Testo',
    },
    {
        title: 'Traduci Testo',
        description: 'Traduzioni multilingua istantanee per testi e frasi.',
        icon: BsTranslate,
        href: '/tools/traduci-testo',
        category: 'Testo',
    },
    {
        title: 'Correttore Grammaticale',
        description: 'Correggi errori grammaticali e migliora lo stile del tuo testo.',
        icon: BsSpellcheck,
        href: '/tools/correttore-grammaticale',
        category: 'Testo',
    },
    {
        title: 'Elabora e Riassumi',
        description: 'Analisi e sintesi avanzata di documenti e articoli.',
        icon: BsTextareaT,
        href: '/tools/elabora-e-riassumi',
        category: 'Testo',
        pro: true,
    },
    {
        title: 'Combina/Splitta PDF',
        description: 'Unisci più PDF in un unico file o dividi un PDF in più parti.',
        icon: BsFileZip,
        href: '/tools/combina-splitta-pdf',
        category: 'PDF',
    },
    {
        title: 'Thumbnail Generator',
        description: 'Crea miniature accattivanti per video e social media.',
        icon: BsCardImage,
        href: '/tools/thumbnail-generator',
        category: 'Immagini',
    },
    {
        title: 'Compressione Video',
        description: 'Riduci le dimensioni dei tuoi file video senza perdere qualità.',
        icon: BsCameraVideo,
        href: '/tools/compressione-video',
        category: 'Video',
        pro: true,
    },
    {
        title: 'Upscaler AI',
        description: 'Migliora la risoluzione delle tue immagini fino a 4x.',
        icon: BsArrowsAngleContract,
        href: '/tools/upscaler-ai',
        category: 'Immagini',
    },
    {
        title: 'Convertitore PDF',
        description: 'Converti facilmente file da e verso PDF: JPG, DOCX e altri formati.',
        icon: BsFileEarmarkPdf,
        href: '/pdf',
        category: 'PDF',
    }
];
