var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/pages/home.js")
R.c("server/chunks/ssr/_78d0a030._.js")
R.c("server/chunks/ssr/_a9d4b89c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__84687bd7._.js")
R.c("server/chunks/ssr/_0420eff1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__dd7cc552._.js")
R.c("server/chunks/ssr/_f713ee1b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__68d47023._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a1b612bf._.js")
R.c("server/chunks/ssr/[root-of-the-server]__4c0d52f8._.js")
R.m(124525)
module.exports=R.m(124525).exports
