var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/pages/pricing.js")
R.c("server/chunks/ssr/[root-of-the-server]__6eb1fd1d._.js")
R.c("server/chunks/ssr/node_modules_next_8683356f._.js")
R.c("server/chunks/ssr/node_modules_react-icons_bs_index_mjs_ad797dda._.js")
R.c("server/chunks/ssr/node_modules_186c80ea._.js")
R.c("server/chunks/ssr/[root-of-the-server]__3c8416e4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__325bc020._.js")
R.c("server/chunks/ssr/node_modules_6a743dce._.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/pages.js { INNER_PAGE => \"[project]/pages/pricing.js [ssr] (ecmascript)\", INNER_DOCUMENT => \"[project]/pages/_document.js [ssr] (ecmascript)\", INNER_APP => \"[project]/pages/_app.js [ssr] (ecmascript)\" } [ssr] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/pages.js { INNER_PAGE => \"[project]/pages/pricing.js [ssr] (ecmascript)\", INNER_DOCUMENT => \"[project]/pages/_document.js [ssr] (ecmascript)\", INNER_APP => \"[project]/pages/_app.js [ssr] (ecmascript)\" } [ssr] (ecmascript)").exports
